version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:latest

master_only: &master_only
  filters:
    branches:
      only: master

jobs:
  # --------------------------------------------------------------------------
  # Phase 1: Setup
  # --------------------------------------------------------------------------
  setup:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      # Save cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # Persist workspace
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  # --------------------------------------------------------------------------
  # Phase 2: Lint + Build
  # --------------------------------------------------------------------------
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .nuxt
            - static/sw.js

  # --------------------------------------------------------------------------
  # Phase 3: Deploy
  # --------------------------------------------------------------------------
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - add_ssh_keys
      - run:
          name: Setup SSH
          command: |
            sudo apt-get install rsync
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run:
          name: Synchronize remote folder
          command: rsync -ra -e "ssh -p $DEPLOY_SSH_PORT" --delete . $DEPLOY_SSH_HOST:$DEPLOY_REMOTE_APP_DIR
      - run:
          name: Reload PM2
          command: ssh -p $DEPLOY_SSH_PORT $DEPLOY_SSH_HOST "cd $DEPLOY_REMOTE_APP_DIR && pm2 reload ecosystem.config.json"


# Workflow definition
workflows:
  version: 2

  # Build and deploy after each commit
  build-and-deploy:
    jobs:
      - setup
      - lint:   { requires: [setup], <<: *master_only }
      - build:  { requires: [setup], <<: *master_only }
      - deploy: { requires: [lint, build], <<: *master_only }
