apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: kube-system
  labels:
    k8s.scw.cloud/ingress: traefik2
spec:
  type: LoadBalancer
  loadBalancerIP: 195.154.71.32
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: webesecure
    port: 443
    targetPort: websecure
  selector:
    app.kubernetes.io/name: traefik
